/* global AFRAME, THREE */
(function () {
  'use strict';

  // Full-screen portal glitch (sampled in main.js via ShaderMaterial)
  window.HackedPortalShaders = {
    vertex: [
      'precision highp float;',
      'uniform float uTime;',
      'uniform float uIntensity;',
      'varying vec2 vUv;',
      '',
      'float hash(vec2 p) {',
      '  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);',
      '}',
      '',
      'void main() {',
      '  vUv = uv;',
      '  vec3 pos = position;',
      '  vec2 g = pos.xy * 6.0;',
      '  float n = sin(g.x + uTime * 1.7) * cos(g.y - uTime * 1.1);',
      '  float m = hash(floor(g + uTime * 0.5)) * 2.0 - 1.0;',
      '  pos.z += (n * 0.55 + m * 0.45) * 0.035 * uIntensity;',
      '  gl_Position = projectionMatrix * modelViewMatrix * vec4(pos, 1.0);',
      '}',
      ''
    ].join('\n'),

    fragment: [
      'precision mediump float;',
      'uniform sampler2D uVideo;',
      'uniform vec2 uResolution;',
      'uniform float uTime;',
      'uniform float uIntensity;',
      'uniform float uSeed;',
      'varying vec2 vUv;',
      '',
      'float hash(vec2 p) {',
      '  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);',
      '}',
      '',
      'float noise(vec2 st) {',
      '  vec2 i = floor(st);',
      '  vec2 f = fract(st);',
      '  float a = hash(i);',
      '  float b = hash(i + vec2(1.0, 0.0));',
      '  float c = hash(i + vec2(0.0, 1.0));',
      '  float d = hash(i + vec2(1.0, 1.0));',
      '  vec2 u = f * f * (3.0 - 2.0 * f);',
      '  return mix(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;',
      '}',
      '',
      'void main() {',
      '  float I = clamp(uIntensity, 0.0, 2.0);',
      '  vec2 uv = vUv;',
      '',
      '  float t = uTime + uSeed * 19.1;',
      '  vec2 blockUv = floor(uv * vec2(48.0, 27.0) + t * 0.7);',
      '  float blk = noise(blockUv * 0.08 + t * 0.15);',
      '  vec2 jitter = (vec2(blk, noise(blockUv * 0.11)) - 0.5) * 0.035 * I;',
      '  uv += jitter;',
      '',
      '  float px = 120.0 + 100.0 * sin(t * 0.65 + blk * 6.28);',
      '  px = max(px * (1.0 - 0.35 * I), 32.0);',
      '  vec2 puv = floor(uv * px) / px;',
      '',
      '  float drift = sin(puv.y * 80.0 + t * 12.0) * 0.0025 * I;',
      '  float ab = (0.004 + 0.002 * sin(t * 3.1 + puv.y * 30.0)) * I;',
      '  vec2 ca = vec2(ab + drift, ab * 0.55);',
      '  vec2 offR = puv + ca + vec2(sin(t * 1.3), 0.0) * 0.01 * I;',
      '  vec2 offG = puv;',
      '  vec2 offB = puv - ca;',
      '  float r = texture2D(uVideo, offR).r;',
      '  float g = texture2D(uVideo, offG).g;',
      '  float b = texture2D(uVideo, offB).b;',
      '  vec3 col = vec3(r, g, b);',
      '',
      '  float scan = sin(puv.y * uResolution.y * 0.85) * 0.5 + 0.5;',
      '  col *= 0.82 + 0.18 * scan;',
      '  float roll = smoothstep(0.0, 0.04, fract(puv.y * uResolution.y / 5.0));',
      '  col *= 0.9 + 0.1 * roll;',
      '',
      '  float diss = noise(puv * 9.0 + t * 2.2);',
      '  float cut = step(0.88 - I * 0.08, diss);',
      '  col = mix(col, col * vec3(0.15, 0.45, 1.0), cut * 0.55 * I);',
      '',
      '  float snow = step(0.97 - I * 0.04, hash(floor(uv * uResolution.xy * 0.08) + t));',
      '  col += vec3(0.08, 0.1, 0.12) * snow * I;',
      '',
      '  gl_FragColor = vec4(col, 1.0);',
      '}',
      ''
    ].join('\n')
  };

  // Marker-world accent: procedural rim on the anchor sphere
  AFRAME.registerShader('my-custom-glow', {
    schema: {
      uTime: { type: 'time', is: 'uniform' },
      uColor: { type: 'color', is: 'uniform', default: '#00ffcc' }
    },
    vertexShader: [
      'varying vec3 vNormal;',
      'varying vec3 vView;',
      'void main() {',
      '  vNormal = normalize(normalMatrix * normal);',
      '  vec4 mvPos = modelViewMatrix * vec4(position, 1.0);',
      '  vView = -mvPos.xyz;',
      '  gl_Position = projectionMatrix * mvPos;',
      '}',
      ''
    ].join('\n'),
    fragmentShader: [
      'precision mediump float;',
      'uniform vec3 uColor;',
      'uniform float uTime;',
      'varying vec3 vNormal;',
      'varying vec3 vView;',
      'void main() {',
      '  vec3 N = normalize(vNormal);',
      '  vec3 V = normalize(vView);',
      '  float fres = pow(1.0 - abs(dot(N, V)), 2.5);',
      '  float pulse = 0.55 + 0.45 * sin(uTime * 0.003 + fres * 8.0);',
      '  float alpha = fres * pulse * 0.85;',
      '  gl_FragColor = vec4(uColor * (0.25 + fres * 1.2), alpha);',
      '}',
      ''
    ].join('\n')
  });
})();
